# Generated by Django 6.0.7 on 2026-08-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('OTHERS', 'Others'), ('ELECTRONICS', 'Electronics'), ('HOUSEHOLD', 'Household'), ('KITCHEN', 'Kitchen'), ('GADGETS', 'Gadgets'), ('FURNITURE', 'Furniture')], default='OTHERS', max_length=15),
        ),
    ]
