# Generated by Django 6.0.7 on 2026-08-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('BUYER', 'Buyer'), ('SELLER', 'Seller'), ('RIDER', 'Rider'), ('MIDDLEMAN', 'Middleman'), ('ADMIN', 'Admin')], default='BUYER', max_length=255),
        ),
    ]
