name: Keep Render Alive
on: 
  schedule:
    - cron: '*/14 * * * *'
  jobs: 
    ping:
      runs-on: ubuntu-latest
      steps: 
        - name: Wake up API
          run: curl -I https://https://market-app-xa3g.onrender.com/