name: Keep Render Alive

on: 
  schedule:
    - cron: '*/14 * * * *'

jobs: 
  ping:
    runs-on: ubuntu-latest
    steps: 
      - name: Wake up API
        run: |
          for i in {1..3}; do
            curl -I https://market-app-xa3g.onrender.com/ || true
            sleep 10
          done